### ISSUE TITLE
problem in line 266

### ISSUE THREAD

**Issue by MARS2280** [PEHGP/kaas#1]
Hello 
When I tried to follow the example, prompt said: 

kaas.py -f t.fasta -t p -n test -m test@126.com -l fungi -w b --justformat -n -o test
Traceback (most recent call last):
  File "kaas.py", line 266, in <module>
    p=CurlWeb(Mail=Email,ResultFileName=OutPut)
TypeError: __init__() takes at least 2 arguments (3 given)

What am I doing wrong?

Thank in advance!

**Comment by PEHGP** [comment]
First,you should submit data to kaas website,then you can download results using part_kaas.py

part_kaas.py jobid email prefix key
